apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: egress
resources:
  - namespace.yaml
  - deployment.yaml
  - egress.gateway.yaml
  - serviceaccount.yaml
  - serviceentry.yaml
  - policies.yaml
